version: "3.9"

services:
  backend:
    build:
      context: ../backend
    image: syncly-backend:local
    restart: unless-stopped
    environment:
      - PORT=4000
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ../frontend
    image: syncly-frontend:local
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://backend:4000
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
